"""Initial tables

Revision ID: 1a420c112992
Revises: 
Create Date: 2025-04-05 22:02:23.581301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a420c112992'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('article', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_article_title', table_name='article')
    op.create_index(op.f('ix_article_article_id'), 'article', ['article_id'], unique=False)
    op.drop_index('idx_article_author', table_name='article_author')
    op.alter_column('article_vector', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('article_vector', 'vector_data',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_article_vector_vector_id'), 'article_vector', ['vector_id'], unique=False)
    op.alter_column('author', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_author_name', table_name='author')
    op.create_index(op.f('ix_author_author_id'), 'author', ['author_id'], unique=False)
    op.alter_column('favorite_articles', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_favorite_articles', table_name='favorite_articles')
    op.alter_column('favorites', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('favorites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_favorites_favorites_id'), 'favorites', ['favorites_id'], unique=False)
    op.alter_column('interface_settings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_interface_settings_settings_id'), 'interface_settings', ['settings_id'], unique=False)
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_user_email', table_name='user')
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.create_index('idx_user_email', 'user', ['email'], unique=False)
    op.alter_column('user', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_interface_settings_settings_id'), table_name='interface_settings')
    op.alter_column('interface_settings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_favorites_favorites_id'), table_name='favorites')
    op.alter_column('favorites', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('favorites', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_favorite_articles', 'favorite_articles', ['article_id'], unique=False)
    op.alter_column('favorite_articles', 'added_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_author_author_id'), table_name='author')
    op.create_index('idx_author_name', 'author', ['name'], unique=False)
    op.alter_column('author', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_article_vector_vector_id'), table_name='article_vector')
    op.alter_column('article_vector', 'vector_data',
               existing_type=sa.NullType(),
               nullable=False)
    op.alter_column('article_vector', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_article_author', 'article_author', ['author_id'], unique=False)
    op.drop_index(op.f('ix_article_article_id'), table_name='article')
    op.create_index('idx_article_title', 'article', ['title'], unique=False)
    op.alter_column('article', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('article', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
